name: radio_cabral
services:
  azuracast:
    image: azuracast/azuracast:latest
    container_name: azuracast
    restart: always
    env_file:
      - .env
    ports:
      - '${AZURACAST_HTTP_PORT:-80}:${AZURACAST_HTTP_PORT:-80}'
      - '${AZURACAST_HTTPS_PORT:-443}:${AZURACAST_HTTPS_PORT:-443}'
      - '${AZURACAST_SFTP_PORT:-2022}:${AZURACAST_SFTP_PORT:-2022}'
      - '8096:8096'
      - '8000:8000'
      - '8005:8005'
    volumes:
      - ./azuracast/station_data:/var/azuracast/stations
      - ./azuracast/backups:/var/azuracast/backups
      - ./azuracast/www_uploads:/var/azuracast/storage/uploads
      - ./azuracast/shoutcast2_install:/var/azuracast/storage/shoutcast2
      - ./azuracast/stereo_tool_install:/var/azuracast/storage/stereo_tool
      - ./azuracast/rsas_install:/var/azuracast/storage/rsas
      - ./azuracast/geolite_install:/var/azuracast/storage/geoip
      - ./azuracast/sftpgo_data:/var/azuracast/storage/sftpgo
      - ./azuracast/acme:/var/azuracast/storage/acme